### ISSUE TITLE
Install failing on dappnode

### ISSUE THREAD

**Issue by Tanariel** [rndlabs/dappnodepackage-swarm#113]
hello,

impossible to install swarm on my dappnode. The announced version is 1.0.21. 

At the end of installation i get this error:
 
 `Command failed: docker-compose -f /usr/src/app/dnp_repo/swarm.public.dappnode.eth/docker-compose.yml up --no-start --remove-orphans <&- Container DAppNodePackage-dashboard.swarm.public.dappnode.eth Creating Container DAppNodePackage-bee.swarm.public.dappnode.eth Creating Container DAppNodePackage-dashboard.swarm.public.dappnode.eth Created Error response from daemon: failed to copy file info for /var/lib/docker/volumes/swarmpublicdappnodeeth_bee-data/_data: failed to chown /var/lib/docker/volumes/swarmpublicdappnodeeth_bee-data/_data: lchown /var/lib/docker/volumes/swarmpublicdappnodeeth_bee-data/_data: operation not permitted `

the disk I’m selecting is an additional ssd that has a volume mounted on /mnt/xxxx and not the system disk. Inside the folder dappnode-volumes/swarm.public.dapnode.eth is correctly created. 

Dappnode report : 

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.81
dappmanager.dnp.dappnode.eth: 0.2.76, commit: ea9a7fcd
https.dnp.dappnode.eth: 0.2.1
ipfs.dnp.dappnode.eth: 0.2.21
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.2
System info
dockerComposeVersion: 1.29.2
dockerServerVersion: 20.10.24+dfsg1
dockerCliVersion: 20.10.24+dfsg1
os: debian
versionCodename: bookworm
architecture: amd64
kernel: 6.1.0-9-amd64
Disk usage: 57%

**Comment by rampall** [comment]
Problem caused most likely by docker not having write permission to the additional ssd that was mounted (probable because of extfat).
Solution: unmounting, reformatting the additional ssd as ext4, and re-mounting

**Comment by mfw78** [comment]
As mentioned by @rampall, this is not related to the package, and is related to the permissions on the nominated storage.
